public void test1() throws AssertionError {
    assert_true(false, "Failure test");
    assert_true(true, "True test");
    assert_true(false, "Failure test 2");
}//test1_run


